site_name: 1com Docs
site_url: https://docs.1com.host/
site_description: 1com Docs
site_author: 1com
copyright: Copyright &copy; 2022 1com
extra:
  generator: false
theme:
  name: material
#  name: flatly
  palette:
    #- primary: black
    - scheme: default
      primary: indigo #black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font: false
  features:
    - scheme
    - header.autohide
    #- navigation.top
    #- navigation.sections
    - navigation.tabs
    - navigation.instant
    #- toc.integrate
    - search.highlight
    - search.suggest
#nav:
#    - ... | index*.md
#    - Guides: guides
#    - Books: books
#    - Labs: labs
#    - Gemstones: gemstones
#    - Release Notes: release_notes
#    - Rocky Linux: https://rockylinux.org
#nav:
#    - Introduction: 'index.md'
#    - 'about.md'
#    - 'Issue Tracker': 'https://example.com/'
plugins:
    - search:
        indexing: 'full'
    - redirects
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
            remove_all_empty_space: true
#        js_files:
#            - my/javascript/dir/file1.js
#            - my/javascript/dir/file2.js
#        css_files:
#            - my/css/dir/file1.css
#            - my/css/dir/file2.css
